apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "cluster1-3578"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "cluster1-3578"
    spec:
      containers:
        - name: "cluster1-3578"
          image: "myregistry8911.azurecr.io/cluster1"
          ports:
          - containerPort: 8080