apiVersion: v1
kind: Service
metadata:
    name: "cluster1-3578"
    labels:
        app: "cluster1-3578"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "cluster1-3578"